/**
 * Copyright (C) 2017 Espros Photonics Corporation
 *
 * @defgroup type_return_value Return Value
 * @brief Return Values of the TOF_COS
 * @ingroup tof_cos
 *
 * @{
 */
#ifndef TYPE_RETURN_VALUE_H_
#define TYPE_RETURN_VALUE_H_

enum TypeReturnValue
{
  TOF_COS_STATUS_OK,
	TOF_COS_STATUS_ERROR_GENERAL,
	TOF_COS_STATUS_ERROR_DATA_ACQUISITION,
	TOF_COS_STATUS_ERROR_SENSOR_COMMUNICATION,
	TOF_COS_STATUS_ERROR_ILLUMINATION,
	TOF_COS_STATUS_ERROR_MODULATION_FREQUENCY,
	TOF_COS_STATUS_ERROR_CALIBRATION_MEMORY,
	TOF_COS_STATUS_ERROR_CALIBRATION_GRAYSCALE,
	TOF_COS_STATUS_ERROR_CALIBRATION_AMBIENT_LIGHT
};

#endif /* TYPE_RETURN_VALUE_H_ */

/** @} */
