#ifndef SRC_TYPE_PIXEL_CODE_H_
#define SRC_TYPE_PIXEL_CODE_H_

#include "TOF_COS_Config.h"

enum TypePixelCode
{
  PIXEL_CODE_LIMIT_FOR_VALID_DATA = 16000 + PIXEL_CODE_OFFSET,
	PIXEL_CODE_LOW_AMPLITUDE = 16001 + PIXEL_CODE_OFFSET,
	PIXEL_CODE_ADC_OVERFLOW = 16002 + PIXEL_CODE_OFFSET,
  PIXEL_CODE_SATURATION = 16003 + PIXEL_CODE_OFFSET,
  PIXEL_CODE_BAD = 16004 + PIXEL_CODE_OFFSET,
	PIXEL_CODE_INTERFERENCE = 16007 + PIXEL_CODE_OFFSET,
	PIXEL_CODE_EDGE_FILTERED = 16008 + PIXEL_CODE_OFFSET
};


#endif //SRC_TYPE_PIXEL_CODE_H_
