#ifndef CAMERASELECTION_H
#define CAMERASELECTION_H
enum CameraSelection_e//EDIT
{
  CAMERA_SELECTION_CAM1 = 0,
  CAMERA_SELECTION_CAM2 = 1,
  CAMERA_SELECTION_CAM3 = 2,
  CAMERA_SELECTION_CAM4 = 3,
};

#endif // CAMERASELECTION_H
