# ----------------------------------------------------------------------------------
# Important! Do not remove this constraint!
# This property ensures that all unused pins are set to high impedance.
# If the constraint is removed, all unused pins have to be set to HiZ in the top level file.
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]
# ----------------------------------------------------------------------------------

set_property BITSTREAM.CONFIG.OVERTEMPPOWERDOWN ENABLE [current_design]
set_property PULLDOWN true [get_ports all_inputs]

#Ports TCMI cam1
set_property PACKAGE_PIN N17 [get_ports vsync_in]
set_property PACKAGE_PIN Y18 [get_ports hsync_in]
set_property PACKAGE_PIN N20 [get_ports dclk_in] 
#set_property PACKAGE_PIN V20 [get_ports xsync_sat_in]

set_property IOSTANDARD LVCMOS18 [get_ports vsync_in]
set_property IOSTANDARD LVCMOS18 [get_ports hsync_in]
set_property IOSTANDARD LVCMOS18 [get_ports dclk_in]
#set_property IOSTANDARD LVCMOS18 [get_ports xsync_sat_in]

#Ports TCMI cam2
set_property PACKAGE_PIN M14 [get_ports vsync_in1]
set_property PACKAGE_PIN M15 [get_ports hsync_in1]
set_property PACKAGE_PIN J18 [get_ports dclk_in1] 
#set_property PACKAGE_PIN V20 [get_ports xsync_sat_in]

set_property IOSTANDARD LVCMOS18 [get_ports vsync_in1]
set_property IOSTANDARD LVCMOS18 [get_ports hsync_in1]
set_property IOSTANDARD LVCMOS18 [get_ports dclk_in1]
#set_property IOSTANDARD LVCMOS18 [get_ports xsync_sat_in]

#Ports TCMI cam3
set_property PACKAGE_PIN T15 [get_ports vsync_in2]
set_property PACKAGE_PIN Y17 [get_ports hsync_in2]
set_property PACKAGE_PIN N18 [get_ports dclk_in2] 
#set_property PACKAGE_PIN V20 [get_ports xsync_sat_in]

set_property IOSTANDARD LVCMOS18 [get_ports vsync_in2]
set_property IOSTANDARD LVCMOS18 [get_ports hsync_in2]
set_property IOSTANDARD LVCMOS18 [get_ports dclk_in2]
#set_property IOSTANDARD LVCMOS18 [get_ports xsync_sat_in]

#Ports TCMI cam4
set_property PACKAGE_PIN E18 [get_ports vsync_in3]
set_property PACKAGE_PIN E19 [get_ports hsync_in3]
set_property PACKAGE_PIN H16 [get_ports dclk_in3] 
#set_property PACKAGE_PIN V20 [get_ports xsync_sat_in]

set_property IOSTANDARD LVCMOS18 [get_ports vsync_in3]
set_property IOSTANDARD LVCMOS18 [get_ports hsync_in3]
set_property IOSTANDARD LVCMOS18 [get_ports dclk_in3]
#set_property IOSTANDARD LVCMOS18 [get_ports xsync_sat_in]

#GPIO's cam1
set_property PACKAGE_PIN T16 [get_ports cam1_vbatt_en]
set_property PACKAGE_PIN V15 [get_ports cam1_reset]
set_property PACKAGE_PIN P18 [get_ports cam1_deser_rst]
set_property IOSTANDARD LVCMOS18 [get_ports cam1_vbatt_en]
set_property IOSTANDARD LVCMOS18 [get_ports cam1_reset]
set_property IOSTANDARD LVCMOS18 [get_ports cam1_deser_rst]

set_property PACKAGE_PIN V16 [get_ports {data_in[0]}]
set_property PACKAGE_PIN W16 [get_ports {data_in[1]}]
set_property PACKAGE_PIN T17 [get_ports {data_in[2]}]
set_property PACKAGE_PIN R18 [get_ports {data_in[3]}]
set_property PACKAGE_PIN W18 [get_ports {data_in[4]}]
set_property PACKAGE_PIN W19 [get_ports {data_in[5]}]
set_property PACKAGE_PIN P15 [get_ports {data_in[6]}]
set_property PACKAGE_PIN P16 [get_ports {data_in[7]}]
set_property PACKAGE_PIN R16 [get_ports {data_in[8]}]
set_property PACKAGE_PIN R17 [get_ports {data_in[9]}]
set_property PACKAGE_PIN V17 [get_ports {data_in[10]}]
set_property PACKAGE_PIN V18 [get_ports {data_in[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[0]}]

#GPIO's cam2
set_property PACKAGE_PIN L19 [get_ports cam2_vbatt_en]
set_property PACKAGE_PIN K17 [get_ports cam2_reset]
set_property PACKAGE_PIN H18 [get_ports cam2_deser_rst]
set_property IOSTANDARD LVCMOS18 [get_ports cam2_vbatt_en]
set_property IOSTANDARD LVCMOS18 [get_ports cam2_reset]
set_property IOSTANDARD LVCMOS18 [get_ports cam2_deser_rst]

set_property PACKAGE_PIN J20 [get_ports {data_in1[0]}]
set_property PACKAGE_PIN H20 [get_ports {data_in1[1]}]
set_property PACKAGE_PIN H15 [get_ports {data_in1[2]}]
set_property PACKAGE_PIN G15 [get_ports {data_in1[3]}]
set_property PACKAGE_PIN L14 [get_ports {data_in1[4]}]
set_property PACKAGE_PIN L15 [get_ports {data_in1[5]}]
set_property PACKAGE_PIN K16 [get_ports {data_in1[6]}]
set_property PACKAGE_PIN J16 [get_ports {data_in1[7]}]
set_property PACKAGE_PIN G20 [get_ports {data_in1[8]}]
set_property PACKAGE_PIN K14 [get_ports {data_in1[9]}]
set_property PACKAGE_PIN J14 [get_ports {data_in1[10]}]
set_property PACKAGE_PIN N15 [get_ports {data_in1[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in1[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in1[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in1[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in1[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in1[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in1[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in1[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in1[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in1[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in1[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in1[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in1[0]}]

#GPIO's cam3
set_property PACKAGE_PIN U17 [get_ports cam3_vbatt_en]
set_property PACKAGE_PIN U15 [get_ports cam3_reset]
set_property PACKAGE_PIN Y14 [get_ports cam3_deser_rst]
set_property IOSTANDARD LVCMOS18 [get_ports cam3_vbatt_en]
set_property IOSTANDARD LVCMOS18 [get_ports cam3_reset]
set_property IOSTANDARD LVCMOS18 [get_ports cam3_deser_rst]

set_property PACKAGE_PIN T12 [get_ports {data_in2[0]}]
set_property PACKAGE_PIN U12 [get_ports {data_in2[1]}]
set_property PACKAGE_PIN V12 [get_ports {data_in2[2]}]
set_property PACKAGE_PIN W13 [get_ports {data_in2[3]}]
set_property PACKAGE_PIN P14 [get_ports {data_in2[4]}]
set_property PACKAGE_PIN R14 [get_ports {data_in2[5]}]
set_property PACKAGE_PIN W14 [get_ports {data_in2[6]}]
set_property PACKAGE_PIN T11 [get_ports {data_in2[7]}]
set_property PACKAGE_PIN T10 [get_ports {data_in2[8]}]
set_property PACKAGE_PIN U13 [get_ports {data_in2[9]}]
set_property PACKAGE_PIN V13 [get_ports {data_in2[10]}]
set_property PACKAGE_PIN T14 [get_ports {data_in2[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in2[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in2[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in2[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in2[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in2[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in2[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in2[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in2[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in2[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in2[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in2[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in2[0]}]

#GPIO's cam4
set_property PACKAGE_PIN L20 [get_ports cam4_vbatt_en]
set_property PACKAGE_PIN L17 [get_ports cam4_reset]
set_property PACKAGE_PIN K18 [get_ports cam4_deser_rst]
set_property IOSTANDARD LVCMOS18 [get_ports cam4_vbatt_en]
set_property IOSTANDARD LVCMOS18 [get_ports cam4_reset]
set_property IOSTANDARD LVCMOS18 [get_ports cam4_deser_rst]

set_property PACKAGE_PIN D19 [get_ports {data_in3[0]}]
set_property PACKAGE_PIN D20 [get_ports {data_in3[1]}]
set_property PACKAGE_PIN F16 [get_ports {data_in3[2]}]
set_property PACKAGE_PIN F17 [get_ports {data_in3[3]}]
set_property PACKAGE_PIN M19 [get_ports {data_in3[4]}]
set_property PACKAGE_PIN M20 [get_ports {data_in3[5]}]
set_property PACKAGE_PIN K19 [get_ports {data_in3[6]}]
set_property PACKAGE_PIN J19 [get_ports {data_in3[7]}]
set_property PACKAGE_PIN C20 [get_ports {data_in3[8]}]
set_property PACKAGE_PIN B20 [get_ports {data_in3[9]}]
set_property PACKAGE_PIN E17 [get_ports {data_in3[10]}]
set_property PACKAGE_PIN D18 [get_ports {data_in3[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in3[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in3[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in3[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in3[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in3[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in3[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in3[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in3[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in3[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in3[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in3[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in3[0]}]

#I2C
set_property PACKAGE_PIN B19 [get_ports IIC_1_0_scl_io]
set_property PACKAGE_PIN A20 [get_ports IIC_1_0_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports IIC_1_0_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports IIC_1_0_scl_io]