# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.cache/wt [current_project]
set_property parent.project_path C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/ip_repo [current_project]
set_property ip_output_repo c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/ip_output_repo [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/new/ip_mux.v
  C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/new/op_demux.v
  C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/new/clockMux1.v
  C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/new/clockMux2.v
  C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/new/clockMux3.v
}
read_vhdl -library xil_defaultlib C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/src/vhdl/jss_oms_top.vhd
add_files C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_SG_sort_0/design_1_axi_dma_SG_sort_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_SG_sort_0/design_1_axi_dma_SG_sort_0.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_SG_sort_0/design_1_axi_dma_SG_sort_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_led_0/design_1_axi_gpio_led_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_led_0/design_1_axi_gpio_led_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_led_0/design_1_axi_gpio_led_0.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_power_reset_0/design_1_axi_gpio_power_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_power_reset_0/design_1_axi_gpio_power_reset_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_power_reset_0/design_1_axi_gpio_power_reset_0.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/bd_afc3_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/bd_afc3_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/bd_afc3_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/bd_afc3_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/bd_afc3_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_dbg_unit_0/design_1_blk_mem_gen_dbg_unit_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_dcs_0/design_1_blk_mem_gen_dcs_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_gs_0/design_1_blk_mem_gen_gs_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_gpio_shutter_0/design_1_gpio_shutter_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_gpio_shutter_0/design_1_gpio_shutter_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_gpio_shutter_0/design_1_gpio_shutter_0.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_1_0/design_1_processing_system7_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_synthesis false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_Sel_0/design_1_axi_gpio_Sel_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_Sel_0/design_1_axi_gpio_Sel_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_Sel_0/design_1_axi_gpio_Sel_0.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_10/design_1_auto_pc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_9/design_1_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_8/design_1_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_7/design_1_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_6/design_1_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_11/design_1_auto_pc_11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/epc660/epc660.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/src/cstrs/epc660.xdc
set_property used_in_implementation false [get_files C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/src/cstrs/epc660.xdc]

read_xdc C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/src/cstrs/epc660_pins.xdc
set_property used_in_implementation false [get_files C:/JSS_OMS660_Delivery200227/SL_JSS_OMS/IP/src/cstrs/epc660_pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top jss_oms_top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef jss_oms_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file jss_oms_top_utilization_synth.rpt -pb jss_oms_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
